// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compile_mlir_to_ptx
Rcpp::List compile_mlir_to_ptx(std::string mlir_text, int compute_capability, int num_warps, int num_ctas, int ptx_version);
RcppExport SEXP _ariel_compile_mlir_to_ptx(SEXP mlir_textSEXP, SEXP compute_capabilitySEXP, SEXP num_warpsSEXP, SEXP num_ctasSEXP, SEXP ptx_versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mlir_text(mlir_textSEXP);
    Rcpp::traits::input_parameter< int >::type compute_capability(compute_capabilitySEXP);
    Rcpp::traits::input_parameter< int >::type num_warps(num_warpsSEXP);
    Rcpp::traits::input_parameter< int >::type num_ctas(num_ctasSEXP);
    Rcpp::traits::input_parameter< int >::type ptx_version(ptx_versionSEXP);
    rcpp_result_gen = Rcpp::wrap(compile_mlir_to_ptx(mlir_text, compute_capability, num_warps, num_ctas, ptx_version));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ariel_compile_mlir_to_ptx", (DL_FUNC) &_ariel_compile_mlir_to_ptx, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ariel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
