// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gpu_launch
SEXP gpu_launch(std::string ptx, std::string kernel_name, Rcpp::List inputs, SEXP output, Rcpp::IntegerVector grid, Rcpp::IntegerVector block, int shared_mem);
RcppExport SEXP _ariel_gpu_launch(SEXP ptxSEXP, SEXP kernel_nameSEXP, SEXP inputsSEXP, SEXP outputSEXP, SEXP gridSEXP, SEXP blockSEXP, SEXP shared_memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ptx(ptxSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel_name(kernel_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type inputs(inputsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type output(outputSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type block(blockSEXP);
    Rcpp::traits::input_parameter< int >::type shared_mem(shared_memSEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_launch(ptx, kernel_name, inputs, output, grid, block, shared_mem));
    return rcpp_result_gen;
END_RCPP
}
// gpu_launch_matmul
SEXP gpu_launch_matmul(std::string ptx, std::string kernel_name, SEXP A, SEXP B, SEXP C, int M, int N, int K, int stride_am, int stride_ak, int stride_bk, int stride_bn, int stride_cm, int stride_cn, Rcpp::IntegerVector grid, Rcpp::IntegerVector block, int shared_mem);
RcppExport SEXP _ariel_gpu_launch_matmul(SEXP ptxSEXP, SEXP kernel_nameSEXP, SEXP ASEXP, SEXP BSEXP, SEXP CSEXP, SEXP MSEXP, SEXP NSEXP, SEXP KSEXP, SEXP stride_amSEXP, SEXP stride_akSEXP, SEXP stride_bkSEXP, SEXP stride_bnSEXP, SEXP stride_cmSEXP, SEXP stride_cnSEXP, SEXP gridSEXP, SEXP blockSEXP, SEXP shared_memSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ptx(ptxSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel_name(kernel_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< SEXP >::type B(BSEXP);
    Rcpp::traits::input_parameter< SEXP >::type C(CSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type stride_am(stride_amSEXP);
    Rcpp::traits::input_parameter< int >::type stride_ak(stride_akSEXP);
    Rcpp::traits::input_parameter< int >::type stride_bk(stride_bkSEXP);
    Rcpp::traits::input_parameter< int >::type stride_bn(stride_bnSEXP);
    Rcpp::traits::input_parameter< int >::type stride_cm(stride_cmSEXP);
    Rcpp::traits::input_parameter< int >::type stride_cn(stride_cnSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type block(blockSEXP);
    Rcpp::traits::input_parameter< int >::type shared_mem(shared_memSEXP);
    rcpp_result_gen = Rcpp::wrap(gpu_launch_matmul(ptx, kernel_name, A, B, C, M, N, K, stride_am, stride_ak, stride_bk, stride_bn, stride_cm, stride_cn, grid, block, shared_mem));
    return rcpp_result_gen;
END_RCPP
}
// gpu_cache_clear
Rcpp::List gpu_cache_clear();
RcppExport SEXP _ariel_gpu_cache_clear() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_cache_clear());
    return rcpp_result_gen;
END_RCPP
}
// gpu_cache_stats
Rcpp::List gpu_cache_stats();
RcppExport SEXP _ariel_gpu_cache_stats() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_cache_stats());
    return rcpp_result_gen;
END_RCPP
}
// compile_mlir_to_ptx
Rcpp::List compile_mlir_to_ptx(std::string mlir_text, int compute_capability, int num_warps, int num_ctas, int ptx_version);
RcppExport SEXP _ariel_compile_mlir_to_ptx(SEXP mlir_textSEXP, SEXP compute_capabilitySEXP, SEXP num_warpsSEXP, SEXP num_ctasSEXP, SEXP ptx_versionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type mlir_text(mlir_textSEXP);
    Rcpp::traits::input_parameter< int >::type compute_capability(compute_capabilitySEXP);
    Rcpp::traits::input_parameter< int >::type num_warps(num_warpsSEXP);
    Rcpp::traits::input_parameter< int >::type num_ctas(num_ctasSEXP);
    Rcpp::traits::input_parameter< int >::type ptx_version(ptx_versionSEXP);
    rcpp_result_gen = Rcpp::wrap(compile_mlir_to_ptx(mlir_text, compute_capability, num_warps, num_ctas, ptx_version));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ariel_gpu_launch", (DL_FUNC) &_ariel_gpu_launch, 7},
    {"_ariel_gpu_launch_matmul", (DL_FUNC) &_ariel_gpu_launch_matmul, 17},
    {"_ariel_gpu_cache_clear", (DL_FUNC) &_ariel_gpu_cache_clear, 0},
    {"_ariel_gpu_cache_stats", (DL_FUNC) &_ariel_gpu_cache_stats, 0},
    {"_ariel_compile_mlir_to_ptx", (DL_FUNC) &_ariel_compile_mlir_to_ptx, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ariel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
