# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compile_mlir_to_ptx <- function(mlir_text, compute_capability, num_warps, num_ctas, ptx_version) {
    .Call(`_ariel_compile_mlir_to_ptx`, mlir_text, compute_capability, num_warps, num_ctas, ptx_version)
}

