# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Launch a GPU Kernel from Compiled PTX
#'
#' @param ptx Character, PTX assembly from mlir_compile()
#' @param kernel_name Character, entry point function name
#' @param inputs List of torch_tensor inputs (must be on CUDA)
#' @param output torch_tensor pre-allocated output (must be on CUDA)
#' @param grid Integer vector of length 3, grid dimensions (blocks)
#' @param block Integer vector of length 3, block dimensions (threads)
#' @param shared_mem Integer, dynamic shared memory bytes
#' @return The output tensor (same as input)
#' @export
gpu_launch <- function(ptx, kernel_name, inputs, output, grid, block, shared_mem = 0L) {
    .Call(`_ariel_gpu_launch`, ptx, kernel_name, inputs, output, grid, block, shared_mem)
}

compile_mlir_to_ptx <- function(mlir_text, compute_capability, num_warps, num_ctas, ptx_version) {
    .Call(`_ariel_compile_mlir_to_ptx`, mlir_text, compute_capability, num_warps, num_ctas, ptx_version)
}

